### PR TITLE
Fixes for "perl in space"

### PR DESCRIPTION
**Pull request by mohawk2**

### CODE REVIEW

**Comment by karenetheridge** [comment]
+1

It would be better still if the command could be specified list-wise, rather than all in one string -- doable with IPC::Open2 instead of a plain old `open("...|")`.

**Comment by mohawk2** [comment]
I agree with that. Interestingly, however, Devel::FindPerl's t/11-tainted.t fails on trying open2, even though other tests try open2 and evidently succeed.

**Comment by karenetheridge** [comment]
+1 again, for mohawk :)

**Comment by rjbs** [comment]
Thanks, merged!

**Pull request merged**
